#line 1 "java_lexer.cc"

#line 3 "java_lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer JavaFlexLexer

#ifdef yyalloc
#define Javaalloc_ALREADY_DEFINED
#else
#define yyalloc Javaalloc
#endif

#ifdef yyrealloc
#define Javarealloc_ALREADY_DEFINED
#else
#define yyrealloc Javarealloc
#endif

#ifdef yyfree
#define Javafree_ALREADY_DEFINED
#else
#define yyfree Javafree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[254] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   77,   75,
       73,   74,   75,   75,   72,   72,   75,   72,   72,   72,
       72,   72,   72,   49,   49,   72,   72,   72,   27,   65,
       72,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   72,   60,   62,   61,   61,   71,   67,
       66,   71,   68,   73,   29,    0,   55,    0,   45,   38,
       46,    0,    0,   43,    1,   41,    2,   42,    0,   53,
       59,    0,   44,   53,   50,   53,   54,   54,   53,   49,
       54,   54,   49,   49,   35,   30,   28,   31,   36,   27,
       48,   27,   27,   27,   27,   11,   27,   27,   27,   27,

        3,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   47,   39,   61,   61,   63,   61,   64,   67,
       69,    0,   55,    0,   55,   56,    0,   56,    0,   40,
       53,    0,   58,   53,   53,    0,   50,   54,   52,   51,
       53,   33,   34,   37,   27,   27,   27,   27,   27,   27,
       27,    9,   27,   27,   27,    8,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   70,    0,    0,    0,   57,
       57,   53,   53,   52,   51,   53,   32,   27,   13,   27,
       27,    4,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   25,   27,    0,    0,   27,

        5,   27,   27,   26,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   10,    0,   27,   27,   27,
       27,   21,   27,   27,   27,   27,   27,   15,   22,   18,
       12,   55,   27,   14,   23,   27,   27,   27,   20,   16,
       27,   19,   27,   27,   27,   27,   27,   27,    6,   17,
       24,    7,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   10,   10,   20,
       21,   22,    1,    1,   23,   24,   23,   25,   23,   25,
       26,   26,   26,   26,   26,   27,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   28,   26,   26,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   43,   50,   51,   52,   53,   54,   55,   56,
       43,   43,   10,   57,   10,   10,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1
    } ;

static const flex_int16_t yy_base[265] =
    {   0,
        0,    0,   55,   56,   57,   58,   60,   62,  430,  431,
       68,  431,  408,   65,  407,   65,  397,  431,  405,   62,
       63,   71,   81,   89,  130,   58,  404,   59,    0,  431,
      403,  388,   64,   56,   54,   63,  113,  384,  116,  383,
       66,  370,  378,   98,  431,  431,  152,  153,  431,  416,
      431,  159,  431,  149,  431,  150,  411,  155,  431,  431,
      431,  407,  153,  431,  431,  431,  431,  431,  401,  171,
      431,    0,  431,  175,  171,  201,    0,   84,    0,    0,
      231,  160,    0,    0,  393,  431,  431,  431,  150,    0,
      431,  362,  361,  377,  371,    0,  358,  356,  362,  356,

        0,  356,  130,  349,  367,  155,  367,  349,  366,  357,
      345,  355,  431,  431,  190,  196,  431,  210,  431,  394,
      431,    0,  431,  196,  209,  431,  386,  385,  384,  431,
      431,  213,    0,  255,  431,  217,    0,    0,  236,  177,
      259,  431,  431,  371,  339,  352,  338,  354,  349,  348,
      334,    0,  192,  332,  345,    0,  338,  327,  328,  334,
      325,  325,  324,  337,  329,    0,  232,  367,  252,  431,
      363,  270,  283,    0,    0,    0,  431,  321,    0,  319,
      316,    0,  321,  329,  328,  315,  330,  313,  328,  327,
      322,  317,  302,  306,  308,    0,  302,  331,  253,  302,

        0,  287,  284,    0,  273,  266,  270,  277,  275,  262,
      277,  276,  264,  274,  265,    0,  299,  268,  251,  246,
      253,    0,  254,  251,  241,  226,  209,    0,    0,    0,
        0,  254,  205,    0,    0,  204,  207,  208,    0,    0,
      205,    0,  190,  193,  186,  186,  133,  134,    0,    0,
        0,    0,  431,  322,  326,  330,  334,  116,  338,  342,
      346,   78,  350,  354
    } ;

static const flex_int16_t yy_def[265] =
    {   0,
      253,    1,  254,  254,  254,  254,  255,  255,  253,  253,
      253,  253,  253,  256,  253,  253,  257,  253,  253,  253,
      253,  253,  253,  253,   24,  253,  253,  253,  258,  253,
      253,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  253,  253,  253,  259,  259,  253,  253,
      253,  253,  253,  253,  253,  256,  253,  256,  253,  253,
      253,  253,  260,  253,  253,  253,  253,  253,  253,  253,
      253,  261,  253,  253,   24,   25,  262,  262,  262,  262,
      262,  262,   25,  262,  253,  253,  253,  253,  253,  258,
      253,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  253,  253,  259,  259,  253,  259,  253,  253,
      253,  263,  253,  264,  256,  253,  253,  253,  253,  253,
      253,  253,  261,  253,  253,  253,  262,  262,  262,   81,
      262,  253,  253,  253,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  263,  264,  253,  264,  253,
      253,  253,  253,  262,  262,  262,  253,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  253,  264,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  253,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  253,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,    0,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253
    } ;

static const flex_int16_t yy_nxt[489] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   25,   25,   26,
       27,   28,   29,   29,   29,   29,   29,   29,   30,   10,
       18,   31,   29,   32,   29,   33,   34,   35,   36,   29,
       29,   37,   29,   29,   29,   29,   38,   29,   39,   40,
       41,   42,   29,   29,   43,   29,   44,   46,   46,   46,
       46,   50,   51,   50,   51,   47,   47,   48,   48,   54,
       57,   54,   60,   65,   52,   67,   52,   85,   86,   88,
       89,  138,   66,   68,   69,   61,   70,   70,   70,   70,
       53,   71,   53,   95,   58,   72,   99,   93,   97,  139,

      139,   73,   74,   96,   75,   75,   75,   76,   94,   98,
      100,   77,   78,   79,   77,   80,   81,  109,  113,   90,
      110,   77,   77,   78,   77,   79,   82,   79,   77,   77,
       77,   77,   77,   80,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   81,   83,   83,   83,   83,  105,
       54,  101,   54,   77,  114,  123,   84,   77,  102,  103,
      125,  128,  116,  118,   77,  106,  117,  119,  107,  121,
      143,  144,  252,  122,   84,  141,  141,  141,  141,   58,
      154,  155,  129,  251,   58,   77,   70,   70,   70,   70,
      134,  134,  134,  134,   77,  131,  158,  137,   77,  135,

      253,  168,  159,  175,  253,   77,  116,  131,  132,  131,
      117,  135,  136,  135,  123,  137,   76,   76,   76,   76,
      118,  175,  250,  249,  119,  169,   77,   77,  172,  172,
      172,  172,  173,  173,  173,  173,  185,  168,   58,  186,
      248,  247,  246,  245,  244,   77,  140,  140,  140,  140,
      243,  139,  139,  140,  140,  140,  242,  199,  217,  123,
      241,  169,  174,  240,  140,  140,  140,  140,  140,  140,
      134,  134,  134,  134,  141,  141,  141,  141,  239,  135,
      174,  169,  169,  176,  238,  172,  172,  172,  172,  237,
      236,  135,  136,  135,  131,  176,  235,  176,  173,  173,

      173,  173,  234,  233,  232,  231,  131,  135,  131,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  135,
      220,  135,   45,   45,   45,   45,   49,   49,   49,   49,
       56,  219,   56,   56,   62,  218,  123,   62,  115,  216,
      115,  115,  127,  215,  127,  127,  133,  214,  133,  133,
      166,  213,  166,  166,  167,  167,  167,  167,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  170,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  184,  183,  182,  181,  180,  179,
      178,  177,  171,  126,  170,  120,  165,  164,  163,  162,

      161,  160,  157,  156,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  142,  130,  126,  124,  120,  112,  111,
      108,  104,   92,   91,   87,   64,   63,   59,   55,  253,
        9,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253
    } ;

static const flex_int16_t yy_chk[489] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    7,    7,    8,    8,    3,    4,    5,    6,   11,
       14,   11,   16,   20,    7,   21,    8,   26,   26,   28,
       28,  262,   20,   21,   22,   16,   22,   22,   22,   22,
        7,   23,    8,   34,   14,   23,   36,   33,   35,   78,

       78,   23,   24,   34,   24,   24,   24,   24,   33,   35,
       36,   24,   24,   24,   24,   24,   24,   41,   44,  258,
       41,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   25,   25,   25,   25,   39,
       54,   37,   54,   25,   44,   56,   25,   25,   37,   37,
       58,   63,   47,   48,   25,   39,   47,   48,   39,   52,
       89,   89,  248,   52,   25,   82,   82,   82,   82,   56,
      103,  103,   63,  247,   58,   25,   70,   70,   70,   70,
       74,   74,   74,   74,   75,   70,  106,   75,   75,   74,

      115,  124,  106,  140,  115,   75,  116,   70,   70,   70,
      116,   74,   74,   74,  125,   75,   76,   76,   76,   76,
      118,  140,  246,  245,  118,  124,   75,   76,  132,  132,
      132,  132,  136,  136,  136,  136,  153,  167,  125,  153,
      244,  243,  241,  238,  237,   76,   81,   81,   81,   81,
      236,  139,  139,   81,   81,   81,  233,  169,  199,  232,
      227,  167,  139,  226,   81,   81,   81,   81,   81,   81,
      134,  134,  134,  134,  141,  141,  141,  141,  225,  134,
      139,  169,  199,  141,  224,  172,  172,  172,  172,  223,
      221,  134,  134,  134,  172,  141,  220,  141,  173,  173,

      173,  173,  219,  218,  217,  215,  172,  173,  172,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  173,
      203,  173,  254,  254,  254,  254,  255,  255,  255,  255,
      256,  202,  256,  256,  257,  200,  198,  257,  259,  197,
      259,  259,  260,  195,  260,  260,  261,  194,  261,  261,
      263,  193,  263,  263,  264,  264,  264,  264,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  181,  180,
      178,  171,  168,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  155,  154,  151,  150,  149,  148,  147,  146,
      145,  144,  129,  128,  127,  120,  112,  111,  110,  109,

      108,  107,  105,  104,  102,  100,   99,   98,   97,   95,
       94,   93,   92,   85,   69,   62,   57,   50,   43,   42,
       40,   38,   32,   31,   27,   19,   17,   15,   13,    9,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "java_lexer.ll"
#line 2 "java_lexer.ll"

#include <string>
#include <stdio.h>
#include <stdbool.h>

#include "java_lexer.hh"

/*
* To store error message
*/
#define MAX_LEN 256
char err_msg[MAX_LEN];

/*
* Comprehensive list of build errors
*/
#define BUILD_ERR_MAX_LEN (1<<20)
char err_build_msg[BUILD_ERR_MAX_LEN];

/*
* Indicate whether the build is successful or not
*/
bool build_success=true;

/*
* To store the current line number (UNNECESSARY since we used locations)
*/
// int yylineno = 0;


/* import the parser's token type into a local typedef */
typedef javacompiler::JavaParser::token token;
typedef javacompiler::JavaParser::token_type token_type;

/* By default yylex returns int, we use token_type. Unfortunately yyterminate
 * by default returns 0, which is not of token_type.  --> WE CAN USE THIS TO TRACK EOF*/ 
#define yyterminate() return token::END

/* 
* Needed to match escape characters 
*/
token_type convert_escape_representation(char c)
{
    char converted_char;
    switch(c)
    {
        case 'a':
            converted_char = '\a'; break;
        case 'b':
            converted_char = '\b'; break;
        case 'e':
            converted_char = '\e'; break;
        case 'f':
            converted_char = '\f'; break;
        case 'n':
            converted_char = '\n'; break; 
        case 'r':
            converted_char = '\r'; break;
        case 't':
            converted_char = '\t'; break;
        case 'v':
            converted_char = '\v'; break;
        default:
            converted_char = c;
    }

    return static_cast<token_type>(converted_char);
}

int representation_as_string(char *A,char *B)
{
    int n=strlen(A),m=0;
    int i=0;
    while(i<=n)
    {
        if(A[i]=='\\')
            B[m]=convert_escape_representation(A[++i]);
        else
            B[m]=A[i];
        i++;
        m++;
    }
    return 1;
}

#line 688 "java_lexer.cc"
/*** Flex Declarations and Options ***/
/* enable c++ scanner class generation */
/* change the name of the scanner class. results in "JavaFlexLexer" */
/* the manual says "somewhat more optimized" */
/* The following paragraph suffices to track locations accurately. Each time
 * yylex is invoked, the begin position is moved onto the end position. 
 * Then when a pattern is matched, its width is added to the end
 * column. !!!Code run each time a pattern is matched!!!.
 */
#line 107 "java_lexer.ll"
#define YY_USER_ACTION  yylloc->columns(yyleng);
#line 700 "java_lexer.cc"
/*** Start Conditions ***/

/***  Regular Expressions Part ***/
/* integer {decimal}|{binary}|{octal}|{hexadecimal} */
/* spacing [ \t\n] */
/* multi_line_comment \/\*([^*]*|\*[^/]+)*\*\/ */
/* array_type \[{spacing}*\] */
#line 708 "java_lexer.cc"

#define INITIAL 0
#define comment 1
#define array_comment 2
#define array 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 138 "java_lexer.ll"


#line 141 "java_lexer.ll"
 /* code to place at the beginning of yylex() */

    // reset location
    yylloc->step();


#line 853 "java_lexer.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 254 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 253 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 147 "java_lexer.ll"
return token::INCREMENT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 148 "java_lexer.ll"
return token::DECREMENT;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 149 "java_lexer.ll"
return token::IF;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 150 "java_lexer.ll"
return token::ELSE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 151 "java_lexer.ll"
return token::CLASS;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 152 "java_lexer.ll"
return token::INTERFACE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 153 "java_lexer.ll"
return token::INSTANCEOF;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 154 "java_lexer.ll"
return token::NEW;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 155 "java_lexer.ll"
return token::FOR;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 156 "java_lexer.ll"
return token::WHILE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 157 "java_lexer.ll"
return token::DO;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 158 "java_lexer.ll"
return token::SWITCH;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 159 "java_lexer.ll"
return token::CASE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 160 "java_lexer.ll"
return token::DEFAULT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 161 "java_lexer.ll"
return token::PUBLIC;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 162 "java_lexer.ll"
return token::PRIVATE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 163 "java_lexer.ll"
return token::PROTECTED;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 "java_lexer.ll"
return token::STATIC;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 165 "java_lexer.ll"
return token::ABSTRACT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 166 "java_lexer.ll"
return token::PACKAGE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 167 "java_lexer.ll"
return token::IMPORT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "java_lexer.ll"
return token::RETURN;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 169 "java_lexer.ll"
return token::EXTENDS;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 170 "java_lexer.ll"
return token::IMPLEMENTS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 171 "java_lexer.ll"
return token::TRUE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 172 "java_lexer.ll"
return token::FALSE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 173 "java_lexer.ll"
{
    // printf("%s", yylval->text);

    // std::cout << std::string(yytext) << std::endl;
    strcpy(yylval->text,yytext);
    return token::ID;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 180 "java_lexer.ll"
return token::EQ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 181 "java_lexer.ll"
return token::NEQ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 182 "java_lexer.ll"
return token::LEQ;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 183 "java_lexer.ll"
return token::GEQ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "java_lexer.ll"
return token::SELF_UNSIGNED_RIGHT_SHIFT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 185 "java_lexer.ll"
return token::SELF_LEFT_SHIFT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 186 "java_lexer.ll"
return token::SELF_RIGHT_SHIFT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 187 "java_lexer.ll"
return token::LEFT_SHIFT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 188 "java_lexer.ll"
return token::RIGHT_SHIFT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 189 "java_lexer.ll"
return token::UNSIGNED_RIGHT_SHIFT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 190 "java_lexer.ll"
return token::LOGICAL_AND;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 191 "java_lexer.ll"
return token::LOGICAL_OR;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 192 "java_lexer.ll"
return token::MORE_ARGS;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 193 "java_lexer.ll"
return token::SELF_PLUS;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 194 "java_lexer.ll"
return token::SELF_MINUS;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 195 "java_lexer.ll"
return token::SELF_TIMES;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 196 "java_lexer.ll"
return token::SELF_DIV;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 197 "java_lexer.ll"
return token::SELF_MOD;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 198 "java_lexer.ll"
return token::SELF_BITWISE_AND;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 199 "java_lexer.ll"
return token::SELF_BITWISE_OR;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 200 "java_lexer.ll"
return token::SELF_BITWISE_XOR;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 202 "java_lexer.ll"
yylval->num=strtol(yytext,NULL,10);return token::INTEGER;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 203 "java_lexer.ll"
yylval->num=strtol(yytext+1,NULL,8);return token::INTEGER;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 204 "java_lexer.ll"
yylval->num=strtol(yytext+2,NULL,16); return token::INTEGER;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 205 "java_lexer.ll"
yylval->num=strtol(yytext+2,NULL,2); return token::INTEGER;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 206 "java_lexer.ll"
yylval->real=strtod(yytext,NULL); return token::REAL;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 208 "java_lexer.ll"
{
    /*
        Note on syntax_error : 
            This class derives from ‘std::runtime_error’.  Throw instances of
            it from the scanner or from the actions to raise parse errors.
            This is equivalent with first invoking ‘error’ (or yyerror in C) to report the
            location and message of the syntax error, and then to invoke
            ‘YYERROR’ to enter the error-recovery mode.
     */
    std::string message = "invalid identifier '" + std::string(yytext) + "'";
    throw javacompiler::JavaParser::syntax_error(*yylloc, message);
}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 221 "java_lexer.ll"
{
    strcpy(yylval->text,yytext+1);
    yylval->text[strlen(yylval->text)-1]=0;
    representation_as_string(yylval->text,yylval->text);
    int m=strlen(yylval->text);
    for(int i=0;i<m;i++)
        if(yylval->text[i]=='\n')
            // yylineno++;
            yylloc->lines(yyleng); yylloc->step();

            
    return token::STRING;   
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 235 "java_lexer.ll"
{
    yylval->character = yytext[0];
    return token::CHARACTER;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 240 "java_lexer.ll"
{
    yylval->character=convert_escape_representation(yytext[1]);
    return token::CHARACTER;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 245 "java_lexer.ll"

	YY_BREAK
case 59:
YY_RULE_SETUP
#line 247 "java_lexer.ll"
{   BEGIN(comment);  }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 248 "java_lexer.ll"
/* skip everything that's not "*" */
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 249 "java_lexer.ll"
/* eat up ’*’s not followed by ’/’s */
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 250 "java_lexer.ll"
{   
                                    //yylineno++;      /* skip (we can use this to count the number of lines later) */
                                    yylloc->lines(yyleng); yylloc->step();
                                }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 254 "java_lexer.ll"
{
                                    /*return to the main routine*/
                                    BEGIN(INITIAL);
                                }
	YY_BREAK
case YY_STATE_EOF(comment):
case YY_STATE_EOF(array_comment):
#line 258 "java_lexer.ll"
{   
                                    BEGIN(INITIAL);
                                    std::string message = "comment not closed properly";                                    
                                    throw javacompiler::JavaParser::syntax_error(*yylloc, message);
                                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 263 "java_lexer.ll"
{   BEGIN(array);    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 266 "java_lexer.ll"
{   BEGIN(array);    }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 267 "java_lexer.ll"
{   
                                    // yylineno++;      
                                    yylloc->lines(yyleng); yylloc->step();
                                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 271 "java_lexer.ll"

	YY_BREAK
case 68:
YY_RULE_SETUP
#line 272 "java_lexer.ll"
{   
                                   BEGIN(INITIAL);
                                   return token::ARRAY; 
                                }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 276 "java_lexer.ll"
{  BEGIN(array_comment);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 277 "java_lexer.ll"

	YY_BREAK
case 71:
YY_RULE_SETUP
#line 278 "java_lexer.ll"
{
                                    BEGIN(INITIAL);
                                    unput(yytext[0]);
                                    return static_cast<token_type>('[');
                                }
	YY_BREAK
case YY_STATE_EOF(array):
#line 283 "java_lexer.ll"
{ 
                                    BEGIN(INITIAL);
                                    std::string message = "unexpected end of file";
                                    throw javacompiler::JavaParser::syntax_error(*yylloc, message);
                                }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 291 "java_lexer.ll"
{
                                // return yytext[0];
                                return static_cast<token_type>(*yytext);
                            }
	YY_BREAK
/* gobble up white-spaces, each time blanks are matched, the begin cursor is moved onto the end
  * cursor to effectively ignore the blanks preceding tokens. */
case 73:
YY_RULE_SETUP
#line 299 "java_lexer.ll"
{
    yylloc->step();
}
	YY_BREAK
/* gobble up end-of-lines */
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 304 "java_lexer.ll"
{
    // yylineno++;
    yylloc->lines(yyleng); yylloc->step();
    //return token::EOL;
}
	YY_BREAK
/* pass all other characters up to bison */
case 75:
YY_RULE_SETUP
#line 312 "java_lexer.ll"
{
    // return static_cast<token_type>(*yytext);

    std::string message = "lexical error, illegal character '" + std::string(yytext) + "'";
    throw javacompiler::JavaParser::syntax_error(*yylloc, message);
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 320 "java_lexer.ll"
ECHO;
	YY_BREAK
#line 1376 "java_lexer.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 254 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 254 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 253);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 320 "java_lexer.ll"


namespace javacompiler {

JavaLexer::JavaLexer(std::istream* in, std::ostream* out) :JavaFlexLexer(in, out)
{}

JavaLexer::~JavaLexer()
{}

}


/* This implementation of JavaFlexLexer::yylex() is required to fill the
 * vtable of the class JavaFlexLexer. We define the scanner's main yylex
 * function via YY_DECL to reside in the Scanner class instead. */

#ifdef yylex
#undef yylex
#endif

int JavaFlexLexer::yylex()
{
    std::cerr << "in JavaFlexLexer::yylex() !" << std::endl;
    return 0;
}

/* When the scanner receives an end-of-file indication from YY_INPUT, it then
 * checks the yywrap() function. If yywrap() returns false (zero), then it is
 * assumed that the function has gone ahead and set up `yyin' to point to
 * another input file, and scanning continues. If it returns true (non-zero),
 * then the scanner terminates, returning 0 to its caller. */

int JavaFlexLexer::yywrap()
{
    return 1;
}

